### PR TITLE
Create documentation about Proxying for cjdns.

### PR DESCRIPTION
**Pull request by Kubuxu**
As it turns out it is fairly easy but not obvious.

### CODE REVIEW

**Comment by thefinn93** [comment]
Changes I'd like to see (others may have different opinions):

* Put a disclaimer at the top stating that this is a bad idea and non ideal and you really should just put cjdns on everything. Perhaps we should have a central link for this sort of thing since proxying to a remote cjdns instance seems to be a thing people like to do.
* Move the `cjdns.pac` file to the docs repo, and make the link relative so we're not dependant on Github.
* Link to this from somewhere relevant, don't just leave it floating on it's own, otherwise no one will find it.

**Comment by Kubuxu** [comment]
I am proxying to Cjdns as I don't won't to setup Cjdns on my Windows machine (also I am proxying through local VM) but I will mention that it is bad idea.
cjdns.pac on the hosting on purpose. It content is in the the doc itself but it is much easier to link it from web.

**Comment by thefinn93** [comment]
The fact that the `.pac` file is on the web is not what I have an issue with. I have an issue with it not being contained in this repository when it easily could be.

**Comment by ansuz** [comment]
what's the status with this?

**Comment by cschmittiey** [comment]
Just looks like it needs a bit if cleaning up. If I get time today, I'll
take a look at it.

**Comment by cschmittiey** [comment]
Taken care of now.

**Pull request merged**
