### PR TITLE
Add documentation for installing via docker

### PR DESCRIPTION
**Pull request by chamunks**
This installation has two methods shown for install the one from the proven image I got inspiration from and the one I suggest which matches recommended docker practices.

### CODE REVIEW

**Comment by Kubuxu** [comment]
IMHO you should link to hyperboria's issues and so on.

**Comment by thefinn93** [comment]
If you could remove the broken image that'd be sweet, other than that :+1:

**Comment by thefinn93** [comment]
For clarification, this line appears to be making a broken image:

```
+[![Docker Build Status](http://hubstatus.container42.com/chamunks/debian-cjdns)](https://registry.hub.docker.com/u/chamunks/debian-cjdns)
```

**Comment by willeponken** [comment]
It isn't broken for me @thefinn93

**Comment by thefinn93** [comment]
Appears to have unbroken (the URL was returning a 404 page). I'm fine with merging if others are.

**Comment by chamunks** [comment]
Let me close this one and file a new one with some updates in a day or so.

**Pull request closed without merging**
